$PagesDir = "C:\Users\Lenovo\Desktop\watch repair\pages"

$ContentReplacements = [ordered]@{
  'content="ChronoLux — Expert watch and jewellery repair services. Battery replacement, strap fitting, servicing, and more. 30+ years of trusted craftsmanship."' = 'content="ChronoLux — Mayfair''s premier luxury watch and fine jewellery atelier. Expert restoration, haute horology servicing, and bespoke care for Rolex, Omega, Cartier, and Patek Philippe since 1992."'
  '<title>ChronoLux | Watch &amp; Jewellery Repair Shop</title>' = '<title>ChronoLux | Luxury Watch &amp; Fine Jewellery Atelier — London</title>'
  '"description": "Professional watch and jewellery repair shop offering battery replacement, strap fitting, servicing, ring resizing, and chain repair."' = '"description": "Premium luxury watch and fine jewellery atelier offering haute horology servicing, bespoke restoration, and white-glove care in Mayfair, London."'
  '<span class="section-label text-gold">Master Craftsmanship Since 1992</span>' = '<span class="section-label text-gold">Mayfair Atelier · Est. 1992</span>'
  '<h1>Precision Repair for Watches &amp; Fine Jewellery</h1>' = '<h1>Where Time Meets Luxury</h1>'
  '<p>Trusted by collectors and everyday wearers alike. From battery changes to full restorations, every piece receives the care it deserves.</p>' = '<p>London''s discerning collectors and connoisseurs trust ChronoLux for haute horology servicing, fine jewellery restoration, and bespoke care — delivered with the discretion and precision your treasures deserve.</p>'
  '<span class="section-label">What We Do</span>' = '<span class="section-label">Our Expertise</span>'
  '<h2 id="services-heading">Our Repair Services</h2>' = '<h2 id="services-heading">Bespoke Watch &amp; Jewellery Services</h2>'
  '<p>Comprehensive care for timepieces and treasured jewellery, handled by certified craftspeople.</p>' = '<p>From haute horology overhauls to delicate gemstone settings — every commission is entrusted to master-certified artisans in our Mayfair atelier.</p>'
  '<h3>Battery Replacement</h3>' = '<h3>Quartz Battery Service</h3>'
  '<p>Quick, professional battery swaps for quartz watches with water-resistance testing included.</p>' = '<p>Precision battery replacement for luxury quartz timepieces, complete with gasket inspection and pressure testing to manufacturer standards.</p>'
  '<h3>Strap &amp; Bracelet Fitting</h3>' = '<h3>Strap &amp; Bracelet Atelier</h3>'
  '<p>Custom strap adjustments, bracelet resizing, and clasp repairs for a perfect fit.</p>' = '<p>Bespoke strap fitting, bracelet sizing, and clasp restoration for leather, alligator, and precious-metal bracelets.</p>'
  '<h3>Watch Servicing</h3>' = '<h3>Haute Horology Servicing</h3>'
  '<p>Full mechanical and automatic servicing with lubrication, regulation, and pressure testing.</p>' = '<p>Complete mechanical and automatic overhauls — disassembly, ultrasonic cleaning, lubrication, regulation, and certified pressure testing.</p>'
  '<h3>Ring Resizing</h3>' = '<h3>Ring Resizing &amp; Refinement</h3>'
  '<p>Expert sizing up or down for gold, platinum, and silver rings without compromising integrity.</p>' = '<p>Invisible resizing for platinum, gold, and diamond-set bands — preserving structural integrity and original design lines.</p>'
  '<h3>Jewellery Cleaning</h3>' = '<h3>Fine Jewellery Restoration</h3>'
  '<p>Ultrasonic and steam cleaning to restore brilliance to diamonds, gemstones, and metals.</p>' = '<p>Professional ultrasonic and steam cleaning to revive the brilliance of diamonds, coloured gemstones, and precious metal settings.</p>'
  '<h3>Chain Repair</h3>' = '<h3>Chain &amp; Clasp Restoration</h3>'
  '<p>Soldering, link replacement, and clasp repair for necklaces, bracelets, and watch chains.</p>' = '<p>Micro-soldering, link replacement, and clasp restoration for necklaces, bracelets, and heirloom chains.</p>'
  '<p>Three decades of dedication to horological and jewellery excellence.</p>' = '<p>Over three decades of uncompromising dedication to haute horology and fine jewellery excellence in the heart of Mayfair.</p>'
  '<h4>30+ Years</h4>' = '<h4>30+ Years Heritage</h4>'
  '<p>Generations of expertise passed down through our master watchmakers.</p>' = '<p>Generations of horological mastery passed from master watchmaker to apprentice in our Bond Street atelier.</p>'
  '<h4>Certified</h4>' = '<h4>Master Certified</h4>'
  '<p>AWCI and NAJ certified technicians with ongoing professional training.</p>' = '<p>AWCI and NAJ certified master craftspeople with continuous training in vintage and contemporary movements.</p>'
  '<h4>90-Day Guarantee</h4>' = '<h4>Lifetime Care</h4>'
  '<p>Every repair backed by our comprehensive workmanship guarantee.</p>' = '<p>Every commission backed by our comprehensive workmanship guarantee and complimentary post-service inspection.</p>'
  '<h4>Free Assessment</h4>' = '<h4>Complimentary Consultation</h4>'
  '<p>No-obligation inspection and quote before any work begins.</p>' = '<p>Private, no-obligation assessment and transparent quotation before any work commences.</p>'
  '<div class="brand-logo">SEIKO</div>' = '<div class="brand-logo">PATEK</div>'
  '<div class="brand-logo">TISSOT</div>' = '<div class="brand-logo">AUDEMARS</div>'
  '<div class="brand-logo">TAG HEUER</div>' = '<div class="brand-logo">JAEGER</div>'
  '<h2 id="reviews-heading">What Our Customers Say</h2>' = '<h2 id="reviews-heading">Voices of Our Distinguished Clients</h2>'
  '<p>"My vintage Omega was running minutes fast. They serviced it beautifully — runs like new and the case looks immaculate."</p>' = '<p>"My 1960s Omega Seamaster was losing minutes daily. ChronoLux returned it running within chronometer spec — the case refinishing is simply museum quality."</p>'
  '<span class="role">Watch Collector, London</span>' = '<span class="role">Private Collector, Mayfair</span>'
  '<p>"Resized my grandmother''s wedding ring with such care. You can''t even tell where the work was done. Absolutely recommend."</p>' = '<p>"They resized my grandmother''s Art Deco diamond ring with extraordinary discretion. The join is invisible — a testament to true artisan skill."</p>'
  '<span class="role">Customer, Manchester</span>' = '<span class="role">Client, Knightsbridge</span>'
  '<p>"Same-day battery replacement on my Seiko and they resealed it properly. Fair price, honest advice, and friendly staff."</p>' = '<p>"White-glove service on my Cartier Tank — battery replaced, seals tested, and returned the same afternoon. The standard one expects in Mayfair."</p>'
  '<span class="role">Customer, Birmingham</span>' = '<span class="role">Client, Belgravia</span>'
  '<h2 id="turnaround-heading" class="text-center mb-4">Typical Turnaround Times</h2>' = '<h2 id="turnaround-heading" class="text-center mb-4">Service Timelines</h2>'
  '<h2 id="cta-heading">Drop In or Book a Consultation</h2>' = '<h2 id="cta-heading">Experience the ChronoLux Difference</h2>'
  '<p>Walk-ins welcome during opening hours, or schedule a drop-off at a time that suits you.</p>' = '<p>Private consultations available by appointment, or visit our Bond Street atelier during opening hours.</p>'
  '<h2 id="newsletter-heading">Join Our Newsletter</h2>' = '<h2 id="newsletter-heading">The ChronoLux Journal</h2>'
  '<p class="mb-4">Care tips, seasonal offers, and workshop news — delivered monthly.</p>' = '<p class="mb-4">Horological insights, jewellery care guides, and exclusive atelier invitations — curated monthly for our patrons.</p>'
  'choose TimeCraft.' = 'choose ChronoLux.'
  'content="Learn about ChronoLux — a London watch and jewellery workshop founded in 1992. Meet our master watchmaker, skilled team, and certified craftspeople."' = 'content="Discover ChronoLux — Mayfair''s luxury watch and fine jewellery atelier since 1992. Meet our master watchmaker, artisan team, and certified craftspeople."'
  '<title>About Us | ChronoLux</title>' = '<title>About ChronoLux | Luxury Watch &amp; Jewellery Atelier — London</title>'
  '<h1>About ChronoLux</h1>' = '<h1>The ChronoLux Atelier</h1>'
  'content="ChronoLux services — watch battery replacement, servicing, crystal repair, and jewellery resizing, cleaning, stone setting, and more. Book online today."' = 'content="ChronoLux luxury services — haute horology servicing, movement restoration, crystal replacement, and fine jewellery resizing, cleaning, and stone setting. Book your consultation today."'
  '<title>Repair Services | ChronoLux</title>' = '<title>Luxury Watch &amp; Jewellery Services | ChronoLux — Mayfair</title>'
  '<h1>Our Repair Services</h1>' = '<h1>Our Bespoke Services</h1>'
  'content="Transparent pricing for watch and jewellery repair at ChronoLux. View estimated costs and turnaround times for batteries, servicing, ring resizing, and more."' = 'content="ChronoLux transparent pricing for luxury watch servicing and fine jewellery restoration in Mayfair. View investment guides and service timelines for haute horology and bespoke jewellery care."'
  '<title>Repair Pricing &amp; Estimates | ChronoLux</title>' = '<title>Service Pricing | ChronoLux — Luxury Watch &amp; Jewellery Atelier</title>'
  '<h1>Repair Pricing &amp; Estimates</h1>' = '<h1>Service Investment Guide</h1>'
  'content="Contact ChronoLux in London — visit us at 48 Bond Street, call +44 20 7946 0958, email hello@chronolux.com, or send a message via our contact form. Open Mon–Fri 9–6, Sat 10–4."' = 'content="Contact ChronoLux at our Mayfair atelier — 48 Bond Street, London W1S 4QT. Call +44 20 7946 0958, email hello@chronolux.com, or enquire online. Open Mon–Fri 9–6, Sat 10–4."'
  '<title>Contact Us | ChronoLux — London Watch &amp; Jewellery Repair</title>' = '<title>Contact ChronoLux | Mayfair Luxury Watch &amp; Jewellery Atelier</title>'
  'content="Expert watch care tips, jewellery maintenance guides, and brand insights from the ChronoLux workshop. Practical advice from certified horologists."' = 'content="Expert horological insights, fine jewellery care guides, and luxury brand knowledge from the ChronoLux atelier. Curated advice from certified master watchmakers."'
  '<title>Blog | Watch Care Tips &amp; Repair Guides — ChronoLux</title>' = '<title>The ChronoLux Journal | Luxury Watch &amp; Jewellery Insights</title>'
  '<h1>Workshop Journal</h1>' = '<h1>The ChronoLux Journal</h1>'
  'content="Schedule a drop-off appointment at ChronoLux. Book online for watch and jewellery repair — battery replacement, servicing, ring resizing, and more."' = 'content="Reserve a private consultation at ChronoLux Mayfair. Book online for luxury watch servicing, fine jewellery restoration, and bespoke atelier services."'
  '<title>Book a Consultation | ChronoLux</title>' = '<title>Book a Consultation | ChronoLux — Mayfair Atelier</title>'
  'content="Page not found — the page you are looking for may have been moved or removed. Return to ChronoLux homepage for watch and jewellery repair services."' = 'content="Page not found — return to ChronoLux, Mayfair''s premier luxury watch and fine jewellery atelier."'
  '<title>404 — Page Not Found | ChronoLux</title>' = '<title>404 — Page Not Found | ChronoLux</title>'
  '<h1 id="error-heading">Time stopped here. Page not found.</h1>' = '<h1 id="error-heading">This page has slipped out of time.</h1>'
  'content="ChronoLux is upgrading our workshop. Sign up for updates and be the first to know when we reopen with expanded services and new facilities."' = 'content="ChronoLux is enhancing our Mayfair atelier. Register for updates on our expanded haute horology facilities and new private consultation suites."'
  '<title>Coming Soon | ChronoLux Workshop Upgrade</title>' = '<title>Coming Soon | ChronoLux Atelier Enhancement</title>'
  '<h1 id="coming-soon-heading">We''re Upgrading Our Workshop</h1>' = '<h1 id="coming-soon-heading">Elevating Our Mayfair Atelier</h1>'
  '<p class="mb-0">Our bench is getting a major overhaul — new equipment, expanded services, and a refreshed space for your treasured timepieces. We will be back shortly.</p>' = '<p class="mb-0">Our Bond Street atelier is undergoing a refined transformation — state-of-the-art horological equipment, expanded private suites, and an elevated space for your most treasured pieces. We return shortly.</p>'
  'content="Professional watch servicing at ChronoLux — full mechanical and automatic overhauls with lubrication, regulation, pressure testing, and a 90-day guarantee. Standard, Express, and Premium tiers available."' = 'content="Haute horology servicing at ChronoLux Mayfair — complete mechanical and automatic overhauls with master regulation, pressure testing, and our comprehensive guarantee. Standard, Express, and Premium tiers."'
  '<title>Watch Servicing | ChronoLux — London</title>' = '<title>Haute Horology Servicing | ChronoLux — Mayfair Atelier</title>'
  '<h1 id="service-overview">Watch Servicing</h1>' = '<h1 id="service-overview">Haute Horology Servicing</h1>'
  'content="Master daily watch care with expert tips from ChronoLux. Learn cleaning, storage, water resistance, and servicing intervals to protect your timepiece for decades."' = 'content="Master luxury watch care with expert guidance from ChronoLux. Learn proper cleaning, storage, water resistance, and servicing intervals to preserve your timepiece for generations."'
  '<title>The Complete Guide to Daily Watch Care | ChronoLux Blog</title>' = '<title>The Complete Guide to Luxury Watch Care | ChronoLux Journal</title>'
  'At ChronoLux, we offer free inspections' = 'At ChronoLux, we offer complimentary private assessments'
  'Portrait of Edmund Hartley' = 'Portrait of Alexander Hartley'
  'master watchmaker at ChronoLux' = 'founder and master watchmaker at ChronoLux'
  'Alexander founded ChronoLux in 1992 after completing his apprenticeship under a Mayfair horologist.' = 'Alexander founded ChronoLux in 1992 after completing his apprenticeship under a Bond Street horologist.'
  'ChronoLux began as a small bench in a Mayfair alley' = 'ChronoLux began as a discreet bench in a Mayfair mews'
  'Thank you for contacting ChronoLux.' = 'Thank you for contacting ChronoLux. Our concierge team will respond personally'
  'Thank you for booking with ChronoLux.' = 'Thank you for reserving your consultation with ChronoLux.'
}

Get-ChildItem $PagesDir -Filter *.html | ForEach-Object {
  $content = [System.IO.File]::ReadAllText($_.FullName)
  $original = $content
  foreach ($pair in $ContentReplacements.GetEnumerator()) {
    $content = $content.Replace($pair.Key, $pair.Value)
  }
  if ($content -ne $original) {
    [System.IO.File]::WriteAllText($_.FullName, $content)
    Write-Host "Content updated: $($_.Name)"
  }
}
Write-Host "Content pass complete."
